version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_db:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    #ports:
    #  - '9090:9090'

  node-exporter:
    image: prom/node-exporter
    container_name: monitoring_nodeexporter
    #ports:
    #  - '9100:9100'

  cadvisor:
    image: google/cadvisor:latest
    container_name: monitoring_cadvisor
    command: 
      - '--housekeeping_interval=10s'
      - '--docker_only=true'
      # remove if you need more metrics
      - '--disable_metrics=disk,diskIO,network,tcp,udp,percpu,sched,process'
    #ports:
    #  - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: grafana/grafana
    container_name: monitoring_grafana
    user: "1000"
    links:
      - "prometheus"
      - "cadvisor"
      - "node-exporter"
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
